import type * as B from "./bindings";
import { call } from "./transport";

/** Shell-only output (not generated by ts-rs). */
export interface AppInfo {
  version: string;
  dataDir: string;
  dbPath: string;
  dbSizeBytes: number;
  logDir: string;
  defaultBackupDir: string;
  schemaVersion: number;
}

/** Typed access to every backend command. Argument names are camelCase (Tauri converts them). */
export const api = {
  app: {
    status: () => call<B.AppStatus>("app_status"),
    ready: () => call<void>("app_ready"),
    info: () => call<AppInfo>("app_info"),
    setupDefaults: () => call<B.SetupDefaults>("setup_defaults"),
    completeSetup: (input: B.SetupInput) => call<B.Actor>("setup_complete", { input }),
    /** First run on a reinstalled / new PC: backups already on this PC, then check and restore one. */
    findBackups: () => call<B.BackupInfo[]>("setup_find_backups"),
    inspectSetupBackup: (path: string) => call<B.BackupCheck>("setup_inspect_backup", { path }),
    restoreSetupBackup: (path: string) => call<B.BackupCheck>("setup_restore", { path }),
    demoSeed: () => call<B.SeedSummary>("demo_seed"),
    openFolder: (which: "backups" | "data" | "logs") => call<void>("open_folder", { which }),
    openCameraSettings: () => call<void>("open_camera_settings"),
    /** Writes the current print view (see lib/pdf) to a PDF file. */
    savePdf: (path: string, paper: "a5" | "a4" | "cards") => call<void>("save_pdf", { path, paper }),
    openFile: (path: string) => call<void>("open_file", { path }),
    revealFile: (path: string) => call<void>("reveal_file", { path }),
  },
  auth: {
    login: (userId: string, pin: string) => call<B.Actor>("auth_login", { userId, pin }),
    autoLogin: () => call<B.Actor>("auth_auto_login"),
    logout: () => call<void>("auth_logout"),
    session: () => call<B.Actor | null>("auth_session"),
    changePin: (currentPin: string, newPin: string) => call<void>("auth_change_pin", { currentPin, newPin }),
  },
  users: {
    list: (includeInactive = true) => call<B.UserSummary[]>("users_list", { includeInactive }),
    create: (input: B.NewUserInput) => call<B.UserSummary>("users_create", { input }),
    update: (input: B.UpdateUserInput) => call<B.UserSummary>("users_update", { input }),
    resetPin: (userId: string, pin: string) => call<void>("users_reset_pin", { userId, pin }),
  },
  settings: {
    get: () => call<B.Settings>("settings_get"),
    update: (update: B.SettingsUpdate) => call<B.Settings>("settings_update", { update }),
    defaultTemplates: (language: B.TemplateLanguage) =>
      call<B.MessageTemplates>("settings_default_templates", { language }),
  },
  plans: {
    list: (includeInactive = false) => call<B.Plan[]>("plans_list", { includeInactive }),
    save: (input: B.PlanInput) => call<B.Plan>("plans_save", { input }),
    remove: (id: string) => call<void>("plans_delete", { id }),
  },
  members: {
    list: (query: B.MemberQuery) => call<B.Page<B.MemberRow>>("members_list", { query }),
    counts: (search?: string | null) => call<B.MemberCounts>("members_counts", { search: search || null }),
    get: (id: string) => call<B.Member>("members_get", { id }),
    quick: (id: string) => call<B.MemberQuick>("members_quick", { id }),
    quickSearch: (term: string, limit = 8) => call<B.MemberQuick[]>("members_quick_search", { term, limit }),
    findByCode: (code: string) => call<B.MemberQuick | null>("members_find_by_code", { code }),
    register: (input: B.RegisterMemberInput) => call<B.RegisterResult>("members_register", { input }),
    update: (id: string, input: B.MemberInput) => call<B.Member>("members_update", { id, input }),
    archive: (id: string, reason?: string | null) =>
      call<void>("members_archive", { id, reason: reason || null }),
    restore: (id: string) => call<void>("members_restore", { id }),
    remove: (id: string) => call<void>("members_delete", { id }),
    setPhoto: (id: string, photo: B.PhotoInput) => call<number>("members_set_photo", { id, photo }),
    removePhoto: (id: string) => call<void>("members_remove_photo", { id }),
    duplicates: (query: B.DuplicateQuery) => call<B.MemberQuick[]>("members_duplicates", { query }),
    nextCode: () => call<string>("members_next_code"),
    suggestions: () => call<B.MemberSuggestions>("members_suggestions"),
  },
  memberships: {
    list: (memberId: string) => call<B.SubscriptionRow[]>("memberships_list", { memberId }),
    preview: (memberId: string, planId?: string | null) =>
      call<B.RenewalPreview>("memberships_preview", { memberId, planId: planId || null }),
    renew: (input: B.RenewInput) => call<B.RenewResult>("memberships_renew", { input }),
    cancel: (id: string, reason: string) => call<void>("memberships_cancel", { id, reason }),
    updateDates: (input: B.UpdateDatesInput) => call<void>("memberships_update_dates", { input }),
  },
  freezes: {
    list: (memberId: string) => call<B.FreezeRow[]>("freezes_list", { memberId }),
    create: (input: B.FreezeInput) => call<B.FreezeRow>("freezes_create", { input }),
    end: (id: string) => call<void>("freezes_end", { id }),
  },
  payments: {
    record: (input: B.RecordPaymentInput) => call<B.PaymentResult>("payments_record", { input }),
    list: (query: B.PaymentQuery) => call<B.PaymentList>("payments_list", { query }),
    receipt: (id: string) => call<B.Receipt>("payments_receipt", { id }),
    invoice: (memberId: string) => call<B.FeeInvoice>("billing_invoice", { memberId }),
    void: (id: string, reason: string) => call<void>("payments_void", { id, reason }),
  },
  charges: {
    add: (input: B.ChargeInput) => call<B.ChargeResult>("charges_add", { input }),
    void: (id: string, reason: string) => call<void>("charges_void", { id, reason }),
    list: (memberId: string) => call<B.ChargeRow[]>("charges_list", { memberId }),
  },
  ledger: {
    get: (memberId: string) => call<B.LedgerEntry[]>("ledger_get", { memberId }),
  },
  dues: {
    list: (query: B.DuesQuery) => call<B.DuesList>("dues_list", { query }),
  },
  attendance: {
    checkIn: (input: B.CheckInInput) => call<B.CheckInResult>("attendance_check_in", { input }),
    today: () => call<B.AttendanceRow[]>("attendance_today"),
    list: (query: B.AttendanceQuery) => call<B.Page<B.AttendanceRow>>("attendance_list", { query }),
    remove: (id: number) => call<void>("attendance_delete", { id }),
    memberDays: (memberId: string, from: string, to: string) =>
      call<B.DayCount[]>("attendance_member_days", { memberId, from, to }),
  },
  expenses: {
    categories: (includeInactive = false) =>
      call<B.ExpenseCategory[]>("expense_categories_list", { includeInactive }),
    saveCategory: (input: B.CategoryInput) => call<B.ExpenseCategory>("expense_categories_save", { input }),
    list: (query: B.ExpenseQuery) => call<B.ExpenseList>("expenses_list", { query }),
    save: (input: B.ExpenseInput) => call<B.Expense>("expenses_save", { input }),
    remove: (id: string, reason?: string | null) =>
      call<void>("expenses_delete", { id, reason: reason || null }),
  },
  measurements: {
    list: (memberId: string) => call<B.Measurement[]>("measurements_list", { memberId }),
    save: (input: B.MeasurementInput) => call<B.Measurement>("measurements_save", { input }),
    remove: (id: string) => call<void>("measurements_delete", { id }),
  },
  messages: {
    send: (input: B.MessageLogInput) => call<void>("messages_send", { input }),
    list: (memberId?: string | null, limit = 100) =>
      call<B.MessageLogRow[]>("messages_list", { memberId: memberId || null, limit }),
    queue: (kind: B.ReminderKind, limit = 200) => call<B.ReminderRow[]>("reminders_queue", { kind, limit }),
    counts: () => call<B.ReminderCounts>("reminders_counts"),
  },
  dashboard: {
    get: () => call<B.Dashboard>("dashboard_get"),
  },
  reports: {
    collections: (range: B.DateRange) => call<B.CollectionsReport>("reports_collections", { range }),
    memberships: (range: B.DateRange) => call<B.MembershipReport>("reports_memberships", { range }),
    attendance: (range: B.DateRange) => call<B.AttendanceReport>("reports_attendance", { range }),
    expenses: (range: B.DateRange) => call<B.ExpenseReport>("reports_expenses", { range }),
    pnl: (year: number) => call<B.PnlReport>("reports_pnl", { year }),
    dailyClosing: (date: string) => call<B.DailyClosing>("reports_daily_closing", { date }),
  },
  audit: {
    list: (query: B.AuditQuery) => call<B.Page<B.AuditRow>>("audit_list", { query }),
  },
  backup: {
    now: () => call<B.BackupResult>("backup_now"),
    status: () => call<B.BackupStatus>("backup_status"),
    inspect: (path: string) => call<B.BackupCheck>("backup_inspect", { path }),
    restore: (path: string) => call<B.BackupCheck>("backup_restore", { path }),
  },
  exports: {
    csv: (request: B.ExportRequest) => call<B.ExportResult>("export_csv", { request }),
  },
};

export type { B };
