// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckInMethod } from "./CheckInMethod";
import type { MemberQuick } from "./MemberQuick";

export type AttendanceRow = { id: number, checkedInAt: string, method: CheckInMethod, recordedBy: string | null, member: MemberQuick, };
