// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DayCount } from "./DayCount";
import type { HourCount } from "./HourCount";
import type { NameCount } from "./NameCount";
import type { TopVisitor } from "./TopVisitor";

export type AttendanceReport = { from: string, to: string, total: number, uniqueMembers: number, avgPerDay: number, byDay: Array<DayCount>, byHour: Array<HourCount>, byWeekday: Array<NameCount>, topMembers: Array<TopVisitor>, };
