// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AttendanceQuery = { from?: string | null, to?: string | null, memberId?: string | null, search?: string | null, page?: number | null, pageSize?: number | null, };
