// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuditQuery = { from?: string | null, to?: string | null, userId?: string | null, 
/**
 * Action prefix, e.g. `payment.` or `member.register`.
 */
action?: string | null, entityId?: string | null, search?: string | null, page?: number | null, pageSize?: number | null, };
