// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackupSettings = { autoBackup: boolean, 
/**
 * Backup folder chosen at setup (a second drive such as D: when the PC has one); `None` = the default.
 */
folder: string | null, 
/**
 * Optional second copy (USB drive, Google Drive folder, ...).
 */
mirrorFolder: string | null, 
/**
 * Automatic backups to keep (manual backups are never deleted automatically).
 */
keepCount: number, intervalHours: number, };
