// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupKind } from "./BackupKind";

export type BackupInfo = { fileName: string, path: string, sizeBytes: number, createdAt: string, kind: BackupKind, };
