// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupInfo } from "./BackupInfo";

export type BackupResult = { info: BackupInfo, mirroredTo: string | null, mirrorError: string | null, pruned: number, };
