// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackupCheck = { ok: boolean, message: string, schemaVersion: number, members: number, payments: number, lastActivity: string | null, gymName: string | null, };
