// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupInfo } from "./BackupInfo";

export type BackupStatus = { 
/**
 * Where backups are saved right now.
 */
folder: string, 
/**
 * False when the chosen folder cannot be used (drive missing) — backups then go to the default folder.
 */
folderAvailable: boolean, 
/**
 * A folder on a second drive, offered when backups sit on the same drive as the data.
 */
saferFolder: string | null, defaultFolder: string, mirrorFolder: string | null, autoBackup: boolean, intervalHours: number, keepCount: number, lastBackupAt: string | null, lastBackupPath: string | null, unsavedChanges: boolean, backups: Array<BackupInfo>, };
