// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberQuick } from "./MemberQuick";

export type BirthdayRow = { member: MemberQuick, dateOfBirth: string, inDays: number, };
