// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CategoryTotal = { categoryId: string, name: string, color: string | null, count: number, total: number, };
