// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChargeKind } from "./ChargeKind";
import type { PaymentEntry } from "./PaymentEntry";

export type ChargeInput = { memberId: string, kind: ChargeKind, description?: string | null, amount: number, discount?: number | null, chargeDate?: string | null, payment?: PaymentEntry | null, };
