// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChargeKind } from "./ChargeKind";
import type { PaidStatus } from "./PaidStatus";

export type ChargeRow = { id: string, kind: ChargeKind, description: string, amount: number, discount: number, netAmount: number, chargeDate: string, subscriptionId: string | null, paidAmount: number, status: PaidStatus, createdByName: string | null, voidedAt: string | null, voidReason: string | null, };
