// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaymentResult } from "./PaymentResult";

export type ChargeResult = { chargeId: string, payment: PaymentResult | null, balanceAfter: number, };
