// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckInOutcome } from "./CheckInOutcome";
import type { MemberQuick } from "./MemberQuick";

export type CheckInResult = { outcome: CheckInOutcome, attendanceId: number | null, checkedInAt: string | null, member: MemberQuick, 
/**
 * Plain-language warnings to show the receptionist (expired, dues, frozen...).
 */
warnings: Array<string>, visitsThisMonth: number, };
