// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTotal } from "./DateTotal";
import type { MethodTotal } from "./MethodTotal";
import type { NameTotal } from "./NameTotal";

export type CollectionsReport = { from: string, to: string, total: number, count: number, average: number, byDay: Array<DateTotal>, byMonth: Array<DateTotal>, byMethod: Array<MethodTotal>, byStaff: Array<NameTotal>, 
/**
 * What was billed in the range (membership, admission, ...), before payments.
 */
billedByKind: Array<NameTotal>, billedTotal: number, discountsTotal: number, voidedCount: number, voidedTotal: number, };
