// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expense } from "./Expense";
import type { MethodTotal } from "./MethodTotal";
import type { NameTotal } from "./NameTotal";
import type { PaymentRow } from "./PaymentRow";

export type DailyClosing = { date: string, payments: Array<PaymentRow>, voided: Array<PaymentRow>, byMethod: Array<MethodTotal>, byStaff: Array<NameTotal>, totalCollected: number, cashCollected: number, expenses: Array<Expense>, totalExpenses: number, cashExpenses: number, 
/**
 * Cash that should be in the drawer: cash collected − cash expenses.
 */
netCash: number, newMembers: number, renewals: number, checkIns: number, };
