// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttendanceRow } from "./AttendanceRow";
import type { BirthdayRow } from "./BirthdayRow";
import type { CategoryTotal } from "./CategoryTotal";
import type { DayPoint } from "./DayPoint";
import type { HeatCell } from "./HeatCell";
import type { Kpis } from "./Kpis";
import type { MemberQuick } from "./MemberQuick";
import type { MethodTotal } from "./MethodTotal";
import type { MonthPoint } from "./MonthPoint";
import type { NameCount } from "./NameCount";
import type { PaymentRow } from "./PaymentRow";

export type Dashboard = { generatedAt: string, today: string, showRevenue: boolean, showExpenses: boolean, kpis: Kpis, months: Array<MonthPoint>, days: Array<DayPoint>, methodsMonth: Array<MethodTotal>, planMix: Array<NameCount>, genderMix: Array<NameCount>, ageGroups: Array<NameCount>, timingMix: Array<NameCount>, sourceMix: Array<NameCount>, areaMix: Array<NameCount>, heatmap: Array<HeatCell>, expenseCategoriesMonth: Array<CategoryTotal>, expiring: Array<MemberQuick>, expiredRecent: Array<MemberQuick>, topDues: Array<MemberQuick>, inactive: Array<MemberQuick>, 
/**
 * False while check-ins are off, or have not been recorded for a full "not visiting" window yet.
 */
inactivityTracked: boolean, birthdays: Array<BirthdayRow>, recentPayments: Array<PaymentRow>, recentCheckIns: Array<AttendanceRow>, };
