// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DueRow } from "./DueRow";
import type { DuesAging } from "./DuesAging";

export type DuesList = { items: Array<DueRow>, total: number, page: number, pageSize: number, totalAmount: number, aging: DuesAging, };
