// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DuesAging = { d030: number, d3160: number, d6190: number, d90Plus: number, };
