// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DuesQuery = { search?: string | null, 
/**
 * `amount` (default), `age` or `name`.
 */
sort?: string | null, includeArchived?: boolean | null, page?: number | null, pageSize?: number | null, };
