// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DuplicateQuery = { phone?: string | null, cnic?: string | null, fullName?: string | null, excludeId?: string | null, };
