// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExpenseInput = { id?: string | null, categoryId: string, amount: number, expenseDate?: string | null, method?: string | null, payee?: string | null, description?: string | null, };
