// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CategoryTotal } from "./CategoryTotal";
import type { DateTotal } from "./DateTotal";
import type { MethodTotal } from "./MethodTotal";

export type ExpenseReport = { from: string, to: string, total: number, byCategory: Array<CategoryTotal>, byMonth: Array<DateTotal>, byMethod: Array<MethodTotal>, };
