// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CategoryTotal } from "./CategoryTotal";
import type { Expense } from "./Expense";

export type ExpenseList = { items: Array<Expense>, total: number, page: number, pageSize: number, totalAmount: number, byCategory: Array<CategoryTotal>, };
