// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportKind } from "./ExportKind";

export type ExportRequest = { kind: ExportKind, from?: string | null, to?: string | null, 
/**
 * Destination file chosen in the save dialog.
 */
path: string, };
