// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChargeRow } from "./ChargeRow";

/**
 * A fee invoice (bill) for one member, built on demand from the ledger (not stored).
 */
export type FeeInvoice = { 
/**
 * `INV-<member ID>-<yymmdd>`: the same member gets the same number on the same day.
 */
number: string, issuedOn: string, memberId: string, memberCode: string, memberName: string, fatherName: string | null, phone: string, cnic: string | null, address: string | null, 
/**
 * Current (or latest) membership.
 */
planName: string | null, periodStart: string | null, periodEnd: string | null, 
/**
 * Every charge not fully paid, plus everything billed since the current membership started (oldest first).
 */
lines: Array<ChargeRow>, total: number, paid: number, due: number, 
/**
 * Overall account balance (negative = advance / credit).
 */
balance: number, 
/**
 * Date of the oldest unpaid charge.
 */
dueSince: string | null, };
