// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FreezeState } from "./FreezeState";

export type FreezeRow = { id: string, subscriptionId: string, startDate: string, endDate: string, days: number, reason: string | null, state: FreezeState, createdAt: string, createdByName: string | null, cancelledAt: string | null, };
