// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GymSettings = { name: string, tagline: string, address: string, city: string, phone: string, whatsapp: string, email: string, 
/**
 * PNG/JPEG data URL, max ~300 KB.
 */
logo: string | null, };
