// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HeatCell = { 
/**
 * 0 = Sunday … 6 = Saturday.
 */
dow: number, hour: number, count: number, };
