// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Kpis = { totalMembers: number, activeMembers: number, activeMembers30dAgo: number, newMembersMonth: number, newMembersPrevPeriod: number, renewalsMonth: number, renewalsPrevPeriod: number, expiringSoon: number, expiredRecent: number, frozen: number, noPlan: number, inactive: number, duesTotal: number, duesMembers: number, advanceTotal: number, collectedToday: number, collectedTodayCount: number, collectedYesterday: number, collectedMonth: number, collectedPrevPeriod: number, collectedPrevMonth: number, expensesMonth: number, expensesPrevPeriod: number, profitMonth: number, checkInsToday: number, checkInsYesterday: number, avgDailyCheckIns: number, uniqueVisitors30d: number, endedLast30d: number, renewedOfEnded: number, 
/**
 * Share (0–100) of memberships that ended in the last 30 days and were renewed.
 */
retentionRate: number | null, avgRevenuePerMember: number, };
