// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LedgerEntry = { id: string, 
/**
 * `charge` or `payment`.
 */
entryType: string, date: string, description: string, debit: number, credit: number, 
/**
 * Running balance after this entry (voided entries do not change it).
 */
balance: number, voided: boolean, receiptNo: string | null, method: string | null, };
