// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Measurement = { id: string, memberId: string, measuredOn: string, weightKg: number | null, heightCm: number | null, bodyFatPct: number | null, chestCm: number | null, waistCm: number | null, hipsCm: number | null, armCm: number | null, thighCm: number | null, bmi: number | null, notes: string | null, createdByName: string | null, createdAt: string, };
