// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MeasurementInput = { id?: string | null, memberId: string, measuredOn?: string | null, weightKg?: number | null, heightCm?: number | null, bodyFatPct?: number | null, chestCm?: number | null, waistCm?: number | null, hipsCm?: number | null, armCm?: number | null, thighCm?: number | null, notes?: string | null, };
