// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Gender } from "./Gender";

/**
 * Member details entered on the registration / edit form.
 */
export type MemberInput = { 
/**
 * Leave empty to generate the next code (e.g. DF-0012). Existing register numbers can be typed in.
 */
memberCode?: string | null, fullName: string, fatherName?: string | null, gender: Gender, dateOfBirth?: string | null, phone: string, whatsapp?: string | null, cnic?: string | null, email?: string | null, address?: string | null, area?: string | null, occupation?: string | null, bloodGroup?: string | null, emergencyName?: string | null, emergencyPhone?: string | null, medicalNotes?: string | null, notes?: string | null, timing?: string | null, source?: string | null, joinDate?: string | null, };
