// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MembershipSettings = { memberCodePrefix: string, memberCodeDigits: number, 
/**
 * A membership with this many days left (or fewer) is "expiring".
 */
expiringSoonDays: number, 
/**
 * Renewals within this many days after expiry continue from the old end date.
 */
lateRenewalGraceDays: number, defaultAdmissionFee: number, 
/**
 * Active members without a visit for this many days are flagged "inactive".
 */
inactiveDays: number, 
/**
 * Record check-ins (attendance) at the desk. Off hides the check-in screens and attendance figures.
 */
trackAttendance: boolean, 
/**
 * A second check-in within this many minutes is ignored.
 */
checkinCooldownMinutes: number, 
/**
 * Refuse check-in for expired / no-plan members instead of only warning.
 */
blockExpiredCheckin: boolean, timings: Array<string>, sources: Array<string>, };
