// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Gender } from "./Gender";
import type { MemberStatus } from "./MemberStatus";

export type MemberRow = { id: string, memberCode: string, fullName: string, fatherName: string | null, phone: string, gender: Gender, timing: string | null, status: MemberStatus, planName: string | null, endDate: string | null, daysLeft: number | null, balance: number, lastVisitAt: string | null, photoVersion: number, joinDate: string, 
/**
 * For member cards printed from the list.
 */
cnic: string | null, bloodGroup: string | null, };
