// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberQuick } from "./MemberQuick";
import type { MembershipMonth } from "./MembershipMonth";
import type { PlanStat } from "./PlanStat";

export type MembershipReport = { from: string, to: string, newMembers: number, renewals: number, ended: number, renewedAfterEnd: number, lapsed: number, cancelled: number, retentionRate: number | null, byPlan: Array<PlanStat>, months: Array<MembershipMonth>, expiringNext30: Array<MemberQuick>, };
