// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Gender } from "./Gender";
import type { MemberFilter } from "./MemberFilter";
import type { MemberSort } from "./MemberSort";

export type MemberQuery = { search?: string | null, filter?: MemberFilter | null, timing?: string | null, gender?: Gender | null, planId?: string | null, sort?: MemberSort | null, descending?: boolean | null, page?: number | null, pageSize?: number | null, };
