// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemberFilter = "all" | "active" | "expiring" | "expired" | "frozen" | "upcoming" | "noPlan" | "dues" | "inactive" | "archived";
