// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Gender } from "./Gender";
import type { MemberStatus } from "./MemberStatus";

/**
 * Compact member summary used in lists, check-in, reminders and the dashboard.
 */
export type MemberQuick = { id: string, memberCode: string, fullName: string, phone: string, gender: Gender, status: MemberStatus, planName: string | null, endDate: string | null, daysLeft: number | null, balance: number, lastVisitAt: string | null, photoVersion: number, };
