// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemberCounts = { all: number, active: number, expiring: number, expired: number, frozen: number, upcoming: number, noPlan: number, dues: number, inactive: number, archived: number, };
