// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemberStatus = "active" | "expiring" | "frozen" | "expired" | "upcoming" | "none" | "archived";
