// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MessageLogInput = { memberId?: string | null, 
/**
 * Template key (`welcome`, `receipt`, `expiryReminder`, ... or `custom`).
 */
template: string, phone: string, body: string, };
