// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MessageTemplates = { welcome: string, receipt: string, renewal: string, expiryReminder: string, expiredReminder: string, duesReminder: string, birthday: string, inactive: string, };
