// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MessageLogRow = { id: string, memberId: string | null, memberName: string | null, memberCode: string | null, template: string, phone: string, body: string, createdAt: string, createdByName: string | null, };
