// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MonthPoint = { month: string, label: string, collected: number, expenses: number, profit: number, newMembers: number, renewals: number, 
/**
 * Memberships that ended in the month and were not renewed (churn).
 */
lapsed: number, activeAtEnd: number, };
