// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fields describing a new membership period (registration and renewal forms).
 */
export type NewMembershipInput = { planId: string, startDate?: string | null, 
/**
 * Override of the computed end date (inclusive).
 */
endDate?: string | null, 
/**
 * Override of the plan's fee for this member.
 */
price?: number | null, discount?: number | null, notes?: string | null, };
