// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MethodTotal } from "./MethodTotal";
import type { PaymentRow } from "./PaymentRow";

export type PaymentList = { items: Array<PaymentRow>, total: number, page: number, pageSize: number, sumAmount: number, byMethod: Array<MethodTotal>, voidedCount: number, voidedAmount: number, 
/**
 * The earliest date the current user may see (staff without revenue access see recent days only).
 */
visibleFrom: string | null, };
