// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PaymentQuery = { from?: string | null, to?: string | null, method?: string | null, receivedBy?: string | null, memberId?: string | null, search?: string | null, includeVoided?: boolean | null, page?: number | null, pageSize?: number | null, };
