// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PaymentRow = { id: string, receiptNo: string, paidAt: string, amount: number, method: string, reference: string | null, note: string | null, memberId: string, memberCode: string, memberName: string, memberPhone: string, planName: string | null, receivedByName: string | null, balanceAfter: number, voidedAt: string | null, voidReason: string | null, };
