// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payment details entered on a form.
 */
export type PaymentEntry = { amount: number, method: string, reference?: string | null, note?: string | null, 
/**
 * `YYYY-MM-DD` or `YYYY-MM-DD HH:MM[:SS]`; defaults to now. Past dates need permission.
 */
paidAt?: string | null, };
