// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PaymentResult = { paymentId: string, receiptNo: string, amount: number, balanceAfter: number, };
