// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Photo captured from the webcam or uploaded: JPEG/PNG as base64 or data URL.
 */
export type PhotoInput = { photo: string, thumb: string, };
