// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DurationUnit } from "./DurationUnit";

export type Plan = { id: string, name: string, durationValue: number, durationUnit: DurationUnit, price: number, description: string | null, color: string | null, isActive: boolean, sortOrder: number, 
/**
 * Members whose current/latest membership uses this plan and is still valid today.
 */
activeMembers: number, createdAt: string, };
