// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DurationUnit } from "./DurationUnit";

export type PlanInput = { id?: string | null, name: string, durationValue: number, durationUnit: DurationUnit, price: number, description?: string | null, color?: string | null, isActive?: boolean | null, sortOrder?: number | null, };
