// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PnlMonth = { month: string, label: string, income: number, expenses: number, profit: number, };
