// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CategoryTotal } from "./CategoryTotal";
import type { PnlMonth } from "./PnlMonth";

export type PnlReport = { year: number, months: Array<PnlMonth>, totalIncome: number, totalExpenses: number, totalProfit: number, expenseCategories: Array<CategoryTotal>, };
