// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line printed on a receipt (snapshot taken when the payment is saved).
 */
export type ReceiptItem = { description: string, amount: number, discount: number, };
