// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReceiptItem } from "./ReceiptItem";

export type Receipt = { paymentId: string, receiptNo: string, paidAt: string, amount: number, method: string, reference: string | null, note: string | null, items: Array<ReceiptItem>, balanceBefore: number, balanceAfter: number, memberId: string, memberCode: string, memberName: string, memberPhone: string, planName: string | null, periodStart: string | null, periodEnd: string | null, receivedBy: string | null, voidedAt: string | null, voidReason: string | null, };
