// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordPaymentInput = { memberId: string, amount: number, method: string, reference?: string | null, note?: string | null, paidAt?: string | null, subscriptionId?: string | null, };
