// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberInput } from "./MemberInput";
import type { NewMembershipInput } from "./NewMembershipInput";
import type { PaymentEntry } from "./PaymentEntry";
import type { PhotoInput } from "./PhotoInput";

export type RegisterMemberInput = { member: MemberInput, photo?: PhotoInput | null, membership?: NewMembershipInput | null, 
/**
 * Admission fee charged now (0 / empty = none). Ignored for existing members.
 */
admissionFee?: number | null, payment?: PaymentEntry | null, 
/**
 * Member joined before the software was used (migrating from the paper register).
 */
existingMember?: boolean | null, };
