// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaymentResult } from "./PaymentResult";

export type RegisterResult = { memberId: string, memberCode: string, subscriptionId: string | null, payment: PaymentResult | null, balance: number, };
