// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberQuick } from "./MemberQuick";

export type ReminderRow = { member: MemberQuick, whatsapp: string | null, dateOfBirth: string | null, 
/**
 * Days until the next birthday (birthday queue only; 0 = today).
 */
birthdayInDays: number | null, lastRemindedAt: string | null, };
