// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReminderCounts = { expiring: number, expired: number, dues: number, birthday: number, inactive: number, };
