// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaymentResult } from "./PaymentResult";

export type RenewResult = { subscriptionId: string, planName: string, startDate: string, endDate: string, netAmount: number, payment: PaymentResult | null, balanceAfter: number, };
