// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaymentEntry } from "./PaymentEntry";

export type RenewInput = { memberId: string, planId: string, startDate?: string | null, endDate?: string | null, price?: number | null, discount?: number | null, notes?: string | null, payment?: PaymentEntry | null, };
