// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RenewalPolicy } from "./RenewalPolicy";

export type RenewalPreview = { memberId: string, planId: string | null, planName: string | null, price: number, startDate: string, endDate: string | null, previousEndDate: string | null, daysSinceExpiry: number | null, policy: RenewalPolicy, note: string, balance: number, };
