// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SecuritySettings = { requireLogin: boolean, 
/**
 * Lock the screen after this many idle minutes (0 = never).
 */
autoLockMinutes: number, staffCanSeeRevenue: boolean, staffCanAddExpenses: boolean, };
