// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SeedSummary = { members: number, subscriptions: number, payments: number, checkIns: number, expenses: number, };
