// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupSettings } from "./BackupSettings";
import type { BillingSettings } from "./BillingSettings";
import type { GymSettings } from "./GymSettings";
import type { MembershipSettings } from "./MembershipSettings";
import type { SecuritySettings } from "./SecuritySettings";
import type { WhatsappSettings } from "./WhatsappSettings";

export type SettingsUpdate = { "section": "gym", "value": GymSettings } | { "section": "membership", "value": MembershipSettings } | { "section": "billing", "value": BillingSettings } | { "section": "whatsapp", "value": WhatsappSettings } | { "section": "backup", "value": BackupSettings } | { "section": "security", "value": SecuritySettings };
