// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GymSettings } from "./GymSettings";
import type { SetupPlan } from "./SetupPlan";

export type SetupInput = { gym: GymSettings, ownerName: string, ownerPin: string, admissionFee: number, plans: Array<SetupPlan>, memberCodePrefix?: string | null, 
/**
 * Where backups go (suggested: a second drive such as D:, so a Windows reinstall cannot wipe them).
 */
backupFolder?: string | null, };
