// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GymSettings } from "./GymSettings";
import type { SetupPlan } from "./SetupPlan";

/**
 * Pre-filled values for the first-run wizard.
 */
export type SetupDefaults = { gym: GymSettings, admissionFee: number, memberCodePrefix: string, plans: Array<SetupPlan>, 
/**
 * Suggested backup folder (see [`SetupInput::backup_folder`]).
 */
backupFolder: string, 
/**
 * True when the suggested folder is on a different drive from Windows.
 */
backupOnOtherDrive: boolean, };
