// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaidStatus } from "./PaidStatus";
import type { SubscriptionKind } from "./SubscriptionKind";
import type { SubscriptionState } from "./SubscriptionState";

export type SubscriptionRow = { id: string, memberId: string, planId: string | null, planName: string, kind: SubscriptionKind, startDate: string, endDate: string, baseEndDate: string, freezeDays: number, notes: string | null, state: SubscriptionState, fee: number, discount: number, netAmount: number, paidAmount: number, paidStatus: PaidStatus, createdAt: string, createdByName: string | null, cancelledAt: string | null, cancelReason: string | null, };
