// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Internal state (not edited from the settings screen).
 */
export type SystemState = { setupCompletedAt: string | null, lastBackupAt: string | null, lastBackupPath: string | null, 
/**
 * App version that last opened this database (a change triggers a "before update" backup).
 */
lastAppVersion: string | null, };
