// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageTemplates } from "./MessageTemplates";
import type { WhatsappOpenWith } from "./WhatsappOpenWith";

export type WhatsappSettings = { openWith: WhatsappOpenWith, templates: MessageTemplates, };
